version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
